name: Dance Robot

on:
  push:
    branches:
      - main

jobs:
  dance-robot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dance Robot
        run: |
          const dancingRobot = `
            \\o/\\o/\\o/
            |       |
           / \\     / \\
          `;
          console.log(dancingRobot);
