name: Dance Robot

on: push

jobs:
  dance-robot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Dance Robot
        run: |
          node .github/actions/dancing-robot.js
